# Values file for DeepSeek-Kokoro integration

deepseekVllm:
  enabled: true
  replicas: 1
  image: ghcr.io/vllm-project/vllm:latest
  resources:
    limits:
      cpu: "8"
      memory: "32G"
      nvidia.com/gpu: "1"
    requests:
      cpu: "4"
      memory: "16G"
      nvidia.com/gpu: "1"
  command: "vllm serve deepseek-ai/DeepSeek-R1-Distill-Llama-8B --max-model-len 2048"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    karpenter.sh/nodepool: gpu-nodepool
  service:
    type: ClusterIP
    port: 8000

kokoroTts:
  enabled: true
  replicas: 1
  # Using hardcoded ECR image URL
  image: 240484791744.dkr.ecr.eu-central-1.amazonaws.com/kokoro-tts:latest
  modelId: "hexgrad/Kokoro-82M"
  langCode: "a"  # 'a' for American English
  resources:
    limits:
      cpu: "4"
      memory: 8G
    requests:
      cpu: "2"
      memory: 4G
  service:
    type: ClusterIP
    port: 8080

integration:
  enabled: true
  replicas: 1
  image: python:3.9-slim
  resources:
    limits:
      cpu: "1"
      memory: 2G
    requests:
      cpu: "0.5"
      memory: 1G
  service:
    type: ClusterIP
    port: 80 
